function createfigure(cdata1)
%CREATEFIGURE(cdata1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 21-Oct-2018 11:49:42

% Create figure
figure1 = figure;
colormap(jet);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');




%xlabel('Population','FontSize',12,'FontWeight','bold','Color','r')

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 5087]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.5 18.5]);

box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'CLim',[1.00 1.04],'FontName','Arial','FontSize',20,'Layer','top',...
    'XTick',[0 1017.25 2034.5 3051.75 4069 5086.25],'XTickLabel',...
    {'-1','0','1','2','3','4'},'YTick',[5 10 15]);
% Create colorbar

% Create ylabel
%ylabel('Interactions','FontSize',30);

% Create xlabel
%xlabel('Time (s)','FontSize',30);

%h = colorbar('peer',axes1); set(get(colorbar,'label'),'string','dF/F','FontSize',30); 


% Create line
annotation(figure1,'line',[0.285 0.285],...
    [0.923295800303909 0.11154929577465],'Color','r','LineWidth',2,'LineStyle','--');

truesize(figure1, [100 150]);

saveas(figure1,'heatmaptest.jpg')


